/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModuleVersionUpdateResponseDTO { 
    version?: number;
    moduleId?: string;
    status?: ModuleVersionUpdateResponseDTO.StatusEnum;
    isComplete?: boolean;
    bulletPoints?: string;
    titleEng?: string;
    levelEng?: string;
    languageEng?: ModuleVersionUpdateResponseDTO.LanguageEngEnum;
    frequencyEng?: string;
    credits?: number;
    hoursTotal?: number;
    hoursSelfStudy?: number;
    hoursPresence?: number;
    examinationAchievementsEng?: string;
    examinationAchievementsPromptEng?: string;
    repetitionEng?: string;
    recommendedPrerequisitesEng?: string;
    contentEng?: string;
    contentPromptEng?: string;
    learningOutcomesEng?: string;
    learningOutcomesPromptEng?: string;
    teachingMethodsEng?: string;
    teachingMethodsPromptEng?: string;
    mediaEng?: string;
    mediaPromptEng?: string;
    literatureEng?: string;
    responsiblesEng?: string;
    lvSwsLecturerEng?: string;
    proposalId: number;
}
export namespace ModuleVersionUpdateResponseDTO {
    export type StatusEnum = 'PENDING_SUBMISSION' | 'PENDING_FEEDBACK' | 'ACCEPTED' | 'REJECTED' | 'OBSOLETE' | 'CANCELLED';
    export const StatusEnum = {
        PendingSubmission: 'PENDING_SUBMISSION' as StatusEnum,
        PendingFeedback: 'PENDING_FEEDBACK' as StatusEnum,
        Accepted: 'ACCEPTED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Obsolete: 'OBSOLETE' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum
    };
    export type LanguageEngEnum = 'English' | 'German';
    export const LanguageEngEnum = {
        English: 'English' as LanguageEngEnum,
        German: 'German' as LanguageEngEnum
    };
}


