/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimilarModule } from './similar-module';


export interface SimilarModulesDTO { 
    similarModules?: Array<SimilarModule>;
}

