/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAiReviewGuidelineDTO { 
    section: CreateAiReviewGuidelineDTO.SectionEnum;
    title: string;
    instruction: string;
    sortOrder?: number;
}
export namespace CreateAiReviewGuidelineDTO {
    export type SectionEnum = 'GENERAL' | 'TITLE_ENG' | 'TITLE_DE' | 'LEVEL_ENG' | 'LANGUAGE_ENG' | 'FREQUENCY_ENG' | 'CREDITS' | 'DURATION' | 'HOURS_LECTURE' | 'HOURS_EXERCISE' | 'HOURS_PRACTICAL' | 'HOURS_SEMINAR' | 'FIRST_SEMESTER_AVAILABLE' | 'SUCCESSOR_MODULE_NAME' | 'HOURS_TOTAL' | 'HOURS_SELF_STUDY' | 'HOURS_PRESENCE' | 'BULLET_POINTS' | 'EXAMINATION_ACHIEVEMENTS' | 'REPETITION' | 'RECOMMENDED_PREREQUISITES' | 'CONTENT' | 'LEARNING_OUTCOMES' | 'TEACHING_METHODS' | 'MEDIA' | 'LITERATURE' | 'RESPONSIBLES' | 'LV_SWS_LECTURER' | 'DEGREE_PROGRAM_ASSIGNMENTS';
    export const SectionEnum = {
        General: 'GENERAL' as SectionEnum,
        TitleEng: 'TITLE_ENG' as SectionEnum,
        TitleDe: 'TITLE_DE' as SectionEnum,
        LevelEng: 'LEVEL_ENG' as SectionEnum,
        LanguageEng: 'LANGUAGE_ENG' as SectionEnum,
        FrequencyEng: 'FREQUENCY_ENG' as SectionEnum,
        Credits: 'CREDITS' as SectionEnum,
        Duration: 'DURATION' as SectionEnum,
        HoursLecture: 'HOURS_LECTURE' as SectionEnum,
        HoursExercise: 'HOURS_EXERCISE' as SectionEnum,
        HoursPractical: 'HOURS_PRACTICAL' as SectionEnum,
        HoursSeminar: 'HOURS_SEMINAR' as SectionEnum,
        FirstSemesterAvailable: 'FIRST_SEMESTER_AVAILABLE' as SectionEnum,
        SuccessorModuleName: 'SUCCESSOR_MODULE_NAME' as SectionEnum,
        HoursTotal: 'HOURS_TOTAL' as SectionEnum,
        HoursSelfStudy: 'HOURS_SELF_STUDY' as SectionEnum,
        HoursPresence: 'HOURS_PRESENCE' as SectionEnum,
        BulletPoints: 'BULLET_POINTS' as SectionEnum,
        ExaminationAchievements: 'EXAMINATION_ACHIEVEMENTS' as SectionEnum,
        Repetition: 'REPETITION' as SectionEnum,
        RecommendedPrerequisites: 'RECOMMENDED_PREREQUISITES' as SectionEnum,
        Content: 'CONTENT' as SectionEnum,
        LearningOutcomes: 'LEARNING_OUTCOMES' as SectionEnum,
        TeachingMethods: 'TEACHING_METHODS' as SectionEnum,
        Media: 'MEDIA' as SectionEnum,
        Literature: 'LITERATURE' as SectionEnum,
        Responsibles: 'RESPONSIBLES' as SectionEnum,
        LvSwsLecturer: 'LV_SWS_LECTURER' as SectionEnum,
        DegreeProgramAssignments: 'DEGREE_PROGRAM_ASSIGNMENTS' as SectionEnum
    };
}


