/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DegreeProgramSpecializationDTO } from './degree-program-specialization-dto';
import { ResponsibleUserDTO } from './responsible-user-dto';
import { ExaminationBoardSummaryDTO } from './examination-board-summary-dto';


export interface DegreeProgramDTO { 
    degreeProgramId: number;
    name: string;
    responsibleUser: ResponsibleUserDTO;
    degreeProgramSpecializations?: Array<DegreeProgramSpecializationDTO>;
    examinationBoard?: ExaminationBoardSummaryDTO;
}

