/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponsibleUserDTO } from './responsible-user-dto';


export interface ExaminationBoardDTO { 
    examinationBoardId?: number;
    name?: string;
    members?: Array<ResponsibleUserDTO>;
}

