/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeedbackDTO { 
    titleFeedback?: string;
    titleAccepted?: boolean;
    titleDeFeedback?: string;
    titleDeAccepted?: boolean;
    bulletPointsFeedback?: string;
    bulletPointsAccepted?: boolean;
    levelFeedback?: string;
    levelAccepted?: boolean;
    languageFeedback?: string;
    languageAccepted?: boolean;
    frequencyFeedback?: string;
    frequencyAccepted?: boolean;
    creditsFeedback?: string;
    creditsAccepted?: boolean;
    durationFeedback?: string;
    durationAccepted?: boolean;
    hoursTotalFeedback?: string;
    hoursTotalAccepted?: boolean;
    hoursSelfStudyFeedback?: string;
    hoursSelfStudyAccepted?: boolean;
    hoursPresenceFeedback?: string;
    hoursPresenceAccepted?: boolean;
    hoursLectureFeedback?: string;
    hoursLectureAccepted?: boolean;
    hoursExerciseFeedback?: string;
    hoursExerciseAccepted?: boolean;
    hoursPracticalFeedback?: string;
    hoursPracticalAccepted?: boolean;
    hoursSeminarFeedback?: string;
    hoursSeminarAccepted?: boolean;
    firstSemesterAvailableFeedback?: string;
    firstSemesterAvailableAccepted?: boolean;
    successorModuleNameFeedback?: string;
    successorModuleNameAccepted?: boolean;
    examinationAchievementsFeedback?: string;
    examinationAchievementsAccepted?: boolean;
    repetitionFeedback?: string;
    repetitionAccepted?: boolean;
    recommendedPrerequisitesFeedback?: string;
    recommendedPrerequisitesAccepted?: boolean;
    contentFeedback?: string;
    contentAccepted?: boolean;
    learningOutcomesFeedback?: string;
    learningOutcomesAccepted?: boolean;
    teachingMethodsFeedback?: string;
    teachingMethodsAccepted?: boolean;
    mediaFeedback?: string;
    mediaAccepted?: boolean;
    literatureFeedback?: string;
    literatureAccepted?: boolean;
    responsiblesFeedback?: string;
    responsiblesAccepted?: boolean;
    lvSwsLecturerFeedback?: string;
    lvSwsLecturerAccepted?: boolean;
}

