/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeedbackCompactDTO { 
    feedbackId?: number;
    requestedFromUserName?: string;
    requestedFromSpecializationName?: string;
    examinationBoardName?: string;
    requiredRole?: FeedbackCompactDTO.RequiredRoleEnum;
    status?: FeedbackCompactDTO.StatusEnum;
    invalidated?: boolean;
}
export namespace FeedbackCompactDTO {
    export type RequiredRoleEnum = 'ADMIN' | 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR' | 'PROGRAM_COORDINATOR' | 'SPECIALIZATION_AREA_COORDINATOR' | 'AI_REVIEW_GUIDELINE_MANAGER';
    export const RequiredRoleEnum = {
        Admin: 'ADMIN' as RequiredRoleEnum,
        QualityManagement: 'QUALITY_MANAGEMENT' as RequiredRoleEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as RequiredRoleEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as RequiredRoleEnum,
        Professor: 'PROFESSOR' as RequiredRoleEnum,
        ProgramCoordinator: 'PROGRAM_COORDINATOR' as RequiredRoleEnum,
        SpecializationAreaCoordinator: 'SPECIALIZATION_AREA_COORDINATOR' as RequiredRoleEnum,
        AiReviewGuidelineManager: 'AI_REVIEW_GUIDELINE_MANAGER' as RequiredRoleEnum
    };
    export type StatusEnum = 'PENDING_FEEDBACK' | 'APPROVED' | 'FEEDBACK_GIVEN' | 'REJECTED';
    export const StatusEnum = {
        PendingFeedback: 'PENDING_FEEDBACK' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        FeedbackGiven: 'FEEDBACK_GIVEN' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


