/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Feedback { 
    feedbackId?: number;
    feedbackFrom?: User;
    assignedReviewer?: User;
    invalidated?: boolean;
    requiredRole?: Feedback.RequiredRoleEnum;
    status: Feedback.StatusEnum;
    submissionDate?: string;
    createdAt?: string;
    titleFeedback?: string;
    titleAccepted?: boolean;
    titleDeFeedback?: string;
    titleDeAccepted?: boolean;
    bulletPointsFeedback?: string;
    bulletPointsAccepted?: boolean;
    levelFeedback?: string;
    levelAccepted?: boolean;
    languageFeedback?: string;
    languageAccepted?: boolean;
    frequencyFeedback?: string;
    frequencyAccepted?: boolean;
    creditsFeedback?: string;
    creditsAccepted?: boolean;
    durationFeedback?: string;
    durationAccepted?: boolean;
    hoursTotalFeedback?: string;
    hoursTotalAccepted?: boolean;
    hoursSelfStudyFeedback?: string;
    hoursSelfStudyAccepted?: boolean;
    hoursPresenceFeedback?: string;
    hoursPresenceAccepted?: boolean;
    hoursLectureFeedback?: string;
    hoursLectureAccepted?: boolean;
    hoursExerciseFeedback?: string;
    hoursExerciseAccepted?: boolean;
    hoursPracticalFeedback?: string;
    hoursPracticalAccepted?: boolean;
    hoursSeminarFeedback?: string;
    hoursSeminarAccepted?: boolean;
    firstSemesterAvailableFeedback?: string;
    firstSemesterAvailableAccepted?: boolean;
    successorModuleNameFeedback?: string;
    successorModuleNameAccepted?: boolean;
    examinationAchievementsFeedback?: string;
    examinationAchievementsAccepted?: boolean;
    repetitionFeedback?: string;
    repetitionAccepted?: boolean;
    recommendedPrerequisitesFeedback?: string;
    recommendedPrerequisitesAccepted?: boolean;
    contentFeedback?: string;
    contentAccepted?: boolean;
    learningOutcomesFeedback?: string;
    learningOutcomesAccepted?: boolean;
    teachingMethodsFeedback?: string;
    teachingMethodsAccepted?: boolean;
    mediaFeedback?: string;
    mediaAccepted?: boolean;
    literatureFeedback?: string;
    literatureAccepted?: boolean;
    responsiblesFeedback?: string;
    responsiblesAccepted?: boolean;
    lvSwsLecturerFeedback?: string;
    lvSwsLecturerAccepted?: boolean;
    allFeedbackPositive?: boolean;
    feedbackGiven?: boolean;
    comment?: string;
}
export namespace Feedback {
    export type RequiredRoleEnum = 'ADMIN' | 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR' | 'PROGRAM_COORDINATOR' | 'SPECIALIZATION_AREA_COORDINATOR' | 'AI_REVIEW_GUIDELINE_MANAGER';
    export const RequiredRoleEnum = {
        Admin: 'ADMIN' as RequiredRoleEnum,
        QualityManagement: 'QUALITY_MANAGEMENT' as RequiredRoleEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as RequiredRoleEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as RequiredRoleEnum,
        Professor: 'PROFESSOR' as RequiredRoleEnum,
        ProgramCoordinator: 'PROGRAM_COORDINATOR' as RequiredRoleEnum,
        SpecializationAreaCoordinator: 'SPECIALIZATION_AREA_COORDINATOR' as RequiredRoleEnum,
        AiReviewGuidelineManager: 'AI_REVIEW_GUIDELINE_MANAGER' as RequiredRoleEnum
    };
    export type StatusEnum = 'PENDING_FEEDBACK' | 'APPROVED' | 'FEEDBACK_GIVEN' | 'REJECTED';
    export const StatusEnum = {
        PendingFeedback: 'PENDING_FEEDBACK' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        FeedbackGiven: 'FEEDBACK_GIVEN' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


