/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeedbackListItemDto { 
    feedbackId: number;
    moduleVersionId: number;
    proposalId: number;
    status: FeedbackListItemDto.StatusEnum;
    proposalCreatedByName: string;
    proposalCreatedById: string;
    moduleVersionTitleEng?: string;
}
export namespace FeedbackListItemDto {
    export type StatusEnum = 'PENDING_FEEDBACK' | 'APPROVED' | 'FEEDBACK_GIVEN' | 'REJECTED';
    export const StatusEnum = {
        PendingFeedback: 'PENDING_FEEDBACK' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        FeedbackGiven: 'FEEDBACK_GIVEN' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum
    };
}


