/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModuleVersionViewFeedbackDTO { 
    feedbackId: number;
    feedbackFromFirstName?: string;
    feedbackFromLastName?: string;
    rejectionComment?: string;
    feedbackRole?: ModuleVersionViewFeedbackDTO.FeedbackRoleEnum;
    feedbackStatus?: ModuleVersionViewFeedbackDTO.FeedbackStatusEnum;
    submissionDate?: string;
}
export namespace ModuleVersionViewFeedbackDTO {
    export type FeedbackRoleEnum = 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR';
    export const FeedbackRoleEnum = {
        QualityManagement: 'QUALITY_MANAGEMENT' as FeedbackRoleEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as FeedbackRoleEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as FeedbackRoleEnum,
        Professor: 'PROFESSOR' as FeedbackRoleEnum
    };
    export type FeedbackStatusEnum = 'PENDING_SUBMISSION' | 'PENDING_FEEDBACK' | 'APPROVED' | 'FEEDBACK_GIVEN' | 'REJECTED' | 'OBSOLETE' | 'CANCELLED';
    export const FeedbackStatusEnum = {
        PendingSubmission: 'PENDING_SUBMISSION' as FeedbackStatusEnum,
        PendingFeedback: 'PENDING_FEEDBACK' as FeedbackStatusEnum,
        Approved: 'APPROVED' as FeedbackStatusEnum,
        FeedbackGiven: 'FEEDBACK_GIVEN' as FeedbackStatusEnum,
        Rejected: 'REJECTED' as FeedbackStatusEnum,
        Obsolete: 'OBSOLETE' as FeedbackStatusEnum,
        Cancelled: 'CANCELLED' as FeedbackStatusEnum
    };
}


