/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeedbackCompactDTO } from './feedback-compact-dto';


export interface ModuleVersionCompactDTO { 
    moduleVersionId?: number;
    version?: number;
    titleEng?: string;
    status?: ModuleVersionCompactDTO.StatusEnum;
    isComplete?: boolean;
    feedbackList?: Array<FeedbackCompactDTO>;
}
export namespace ModuleVersionCompactDTO {
    export type StatusEnum = 'PENDING_FIRST_SUBMISSION' | 'PENDING_COORDINATOR_FEEDBACK' | 'COORDINATOR_FEEDBACK_GIVEN' | 'PENDING_FULL_SUBMISSION' | 'PENDING_FULL_FEEDBACK' | 'ACCEPTED' | 'REQUIRES_REVIEW' | 'REJECTED' | 'CANCELLED';
    export const StatusEnum = {
        PendingFirstSubmission: 'PENDING_FIRST_SUBMISSION' as StatusEnum,
        PendingCoordinatorFeedback: 'PENDING_COORDINATOR_FEEDBACK' as StatusEnum,
        CoordinatorFeedbackGiven: 'COORDINATOR_FEEDBACK_GIVEN' as StatusEnum,
        PendingFullSubmission: 'PENDING_FULL_SUBMISSION' as StatusEnum,
        PendingFullFeedback: 'PENDING_FULL_FEEDBACK' as StatusEnum,
        Accepted: 'ACCEPTED' as StatusEnum,
        RequiresReview: 'REQUIRES_REVIEW' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum
    };
}


