/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { School } from './school';


export interface PageResponseDTOSchool { 
    content?: Array<School>;
    totalElements?: number;
    totalPages?: number;
    number?: number;
    size?: number;
}

