/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './user-dto';


export interface PageResponseDTOUserDTO { 
    content?: Array<UserDTO>;
    totalElements?: number;
    totalPages?: number;
    number?: number;
    size?: number;
}

