/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProposalAiReviewSectionDTO } from './proposal-ai-review-section-dto';


export interface ProposalAiReviewDTO { 
    moduleVersionId?: number;
    summary?: string;
    sections?: Array<ProposalAiReviewSectionDTO>;
    generatedAt?: string;
    guidelinesConfigured?: boolean;
}

