/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleDegreeProgramAssignmentDTO } from './module-degree-program-assignment-dto';


export interface ProposalRequestDTO { 
    bulletPoints?: string;
    titleEng: string;
    titleDe?: string;
    levelEng?: string;
    languageEng?: ProposalRequestDTO.LanguageEngEnum;
    frequencyEng?: string;
    credits?: number;
    hoursLecture?: number;
    hoursExercise?: number;
    hoursPractical?: number;
    hoursSeminar?: number;
    firstSemesterAvailable?: string;
    successorModuleName?: string;
    degreeProgramAssignments?: Array<ModuleDegreeProgramAssignmentDTO>;
    duration?: string;
    hoursTotal?: number;
    hoursSelfStudy?: number;
    hoursPresence?: number;
    examinationAchievementsEng?: string;
    examinationAchievementsPromptEng?: string;
    repetitionEng?: string;
    recommendedPrerequisitesEng?: string;
    contentEng?: string;
    contentPromptEng?: string;
    learningOutcomesEng?: string;
    learningOutcomesPromptEng?: string;
    teachingMethodsEng?: string;
    teachingMethodsPromptEng?: string;
    mediaEng?: string;
    literatureEng?: string;
    responsiblesEng?: string;
    lvSwsLecturerEng?: string;
}
export namespace ProposalRequestDTO {
    export type LanguageEngEnum = 'English' | 'German';
    export const LanguageEngEnum = {
        English: 'English' as LanguageEngEnum,
        German: 'German' as LanguageEngEnum
    };
}


