/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProposalsCompactDTO { 
    proposalId?: number;
    createdBy?: string;
    status?: ProposalsCompactDTO.StatusEnum;
    latestVersion?: number;
    latestTitle?: string;
}
export namespace ProposalsCompactDTO {
    export type StatusEnum = 'WAITING_FOR_COORDINATORS_SUBMISSION' | 'PENDING_COORDINATORS_FEEDBACK' | 'COORDINATORS_FEEDBACK_GIVEN' | 'WAITING_FOR_EXAMINATION_BOARD_SUBMISSION' | 'PENDING_EXAMINATION_BOARD_FEEDBACK' | 'EXAMINATION_BOARD_FEEDBACK_GIVEN' | 'WAITING_FOR_QUALITY_MANAGEMENT_SUBMISSION' | 'PENDING_QUALITY_MANAGEMENT_FEEDBACK' | 'ACCEPTED' | 'REQUIRES_REVIEW' | 'REJECTED_AT_COORDINATORS_FEEDBACK' | 'REJECTED_AT_EXAMINATION_BOARD_FEEDBACK' | 'CANCELLED';
    export const StatusEnum = {
        WaitingForCoordinatorsSubmission: 'WAITING_FOR_COORDINATORS_SUBMISSION' as StatusEnum,
        PendingCoordinatorsFeedback: 'PENDING_COORDINATORS_FEEDBACK' as StatusEnum,
        CoordinatorsFeedbackGiven: 'COORDINATORS_FEEDBACK_GIVEN' as StatusEnum,
        WaitingForExaminationBoardSubmission: 'WAITING_FOR_EXAMINATION_BOARD_SUBMISSION' as StatusEnum,
        PendingExaminationBoardFeedback: 'PENDING_EXAMINATION_BOARD_FEEDBACK' as StatusEnum,
        ExaminationBoardFeedbackGiven: 'EXAMINATION_BOARD_FEEDBACK_GIVEN' as StatusEnum,
        WaitingForQualityManagementSubmission: 'WAITING_FOR_QUALITY_MANAGEMENT_SUBMISSION' as StatusEnum,
        PendingQualityManagementFeedback: 'PENDING_QUALITY_MANAGEMENT_FEEDBACK' as StatusEnum,
        Accepted: 'ACCEPTED' as StatusEnum,
        RequiresReview: 'REQUIRES_REVIEW' as StatusEnum,
        RejectedAtCoordinatorsFeedback: 'REJECTED_AT_COORDINATORS_FEEDBACK' as StatusEnum,
        RejectedAtExaminationBoardFeedback: 'REJECTED_AT_EXAMINATION_BOARD_FEEDBACK' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum
    };
}


