/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimilarModuleDTO { 
    moduleId?: string;
    titleEng?: string;
    levelEng?: string;
    languageEng?: string;
    frequencyEng?: string;
    credits?: number;
    duration?: string;
    hoursTotal?: number;
    hoursSelfStudy?: number;
    hoursPresence?: number;
    examinationAchievementsEng?: string;
    examinationAchievementsPromptEng?: string;
    repetitionEng?: string;
    recommendedPrerequisitesEng?: string;
    contentEng?: string;
    contentPromptEng?: string;
    learningOutcomesEng?: string;
    learningOutcomesPromptEng?: string;
    teachingMethodsEng?: string;
    teachingMethodsPromptEng?: string;
    mediaEng?: string;
    literatureEng?: string;
    responsiblesEng?: string;
    lvSwsLecturerEng?: string;
    similarity?: number;
}

