/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRoleDTO { 
    roles: Array<UpdateUserRoleDTO.RolesEnum>;
}
export namespace UpdateUserRoleDTO {
    export type RolesEnum = 'ADMIN' | 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR';
    export const RolesEnum = {
        Admin: 'ADMIN' as RolesEnum,
        QualityManagement: 'QUALITY_MANAGEMENT' as RolesEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as RolesEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as RolesEnum,
        Professor: 'PROFESSOR' as RolesEnum
    };
}


