/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    userId?: string;
    userName?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    roles?: Array<User.RolesEnum>;
}
export namespace User {
    export type RolesEnum = 'ADMIN' | 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR';
    export const RolesEnum = {
        Admin: 'ADMIN' as RolesEnum,
        QualityManagement: 'QUALITY_MANAGEMENT' as RolesEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as RolesEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as RolesEnum,
        Professor: 'PROFESSOR' as RolesEnum
    };
}


