/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDTO { 
    userId?: string;
    userName?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    role?: UserDTO.RoleEnum;
}
export namespace UserDTO {
    export type RoleEnum = 'ADMIN' | 'QUALITY_MANAGEMENT' | 'ACADEMIC_PROGRAM_ADVISOR' | 'EXAMINATION_BOARD' | 'PROFESSOR' | 'UNDEFINED';
    export const RoleEnum = {
        Admin: 'ADMIN' as RoleEnum,
        QualityManagement: 'QUALITY_MANAGEMENT' as RoleEnum,
        AcademicProgramAdvisor: 'ACADEMIC_PROGRAM_ADVISOR' as RoleEnum,
        ExaminationBoard: 'EXAMINATION_BOARD' as RoleEnum,
        Professor: 'PROFESSOR' as RoleEnum,
        Undefined: 'UNDEFINED' as RoleEnum
    };
}


