/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Feedback } from '../model/models';
import { FeedbackListItemDto } from '../model/models';
import { ModuleVersionUpdateRequestDTO } from '../model/models';
import { RejectFeedbackDTO } from '../model/models';
import { UserIdDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FeedbackControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param feedbackId 
     * @param userIdDTO 
     */
    approveFeedback(feedbackId: number, userIdDTO: UserIdDTO, extraHttpRequestParams?: any): Observable<Feedback>;

    /**
     * 
     * 
     * @param id 
     */
    getFeedbacksForUser(id: number, extraHttpRequestParams?: any): Observable<Array<FeedbackListItemDto>>;

    /**
     * 
     * 
     * @param feedbackId 
     */
    getModuleVersionOfFeedback(feedbackId: number, extraHttpRequestParams?: any): Observable<ModuleVersionUpdateRequestDTO>;

    /**
     * 
     * 
     * @param feedbackId 
     * @param rejectFeedbackDTO 
     */
    rejectFeedback(feedbackId: number, rejectFeedbackDTO: RejectFeedbackDTO, extraHttpRequestParams?: any): Observable<Feedback>;

}
