/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ModuleVersion } from '../model/models';
import { ModuleVersionUpdateRequestDTO } from '../model/models';
import { UserIdDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ModuleVersionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param moduleVersionId 
     * @param request 
     */
    getModuleVersionUpdateDtoFromId(moduleVersionId: number, request: UserIdDTO, extraHttpRequestParams?: any): Observable<ModuleVersionUpdateRequestDTO>;

    /**
     * 
     * 
     * @param moduleVersionId 
     * @param moduleVersionUpdateRequestDTO 
     */
    updateModuleVersion(moduleVersionId: number, moduleVersionUpdateRequestDTO: ModuleVersionUpdateRequestDTO, extraHttpRequestParams?: any): Observable<ModuleVersion>;

}
