/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CitModule } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ModuleControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param citModule 
     */
    createModule(citModule: CitModule, extraHttpRequestParams?: any): Observable<CitModule>;

    /**
     * 
     * 
     * @param id 
     */
    deleteModule(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllModules(extraHttpRequestParams?: any): Observable<Array<CitModule>>;

    /**
     * 
     * 
     * @param id 
     */
    getModuleById(id: number, extraHttpRequestParams?: any): Observable<CitModule>;

    /**
     * 
     * 
     * @param id 
     */
    getModuleByModuleId(id: string, extraHttpRequestParams?: any): Observable<CitModule>;

    /**
     * 
     * 
     * @param id 
     * @param citModule 
     */
    updateModule(id: number, citModule: CitModule, extraHttpRequestParams?: any): Observable<CitModule>;

}
