services:
  postgres:
    image: "postgres:latest"
    container_name: module-management-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - module-management-network
    restart: unless-stopped

  ai-service:
    build:
      context: ./AI
      dockerfile: ai.Dockerfile
    container_name: module-management-ai
    volumes:
      - overlap_data:/code/data
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_MODEL: ${AI_MODEL}
    ports:
      - "${AI_SERVICE_PORT}:5000"
    networks:
      - module-management-network
    restart: unless-stopped

volumes:
  postgres_data:
  overlap_data:


networks:
  module-management-network:
    driver: bridge
