services:
  postgres:
    image: 'postgres:latest'
    container_name: module-management-db
    environment:
      - 'POSTGRES_DB=ModuleManagement'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: module-management-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - "8081:8080"