openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/modules/{id}:
    put:
      tags:
      - module-controller
      operationId: updateModule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CitModule"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CitModule"
    delete:
      tags:
      - module-controller
      operationId: deleteModule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/modules/create:
    post:
      tags:
      - module-controller
      operationId: createModule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CitModule"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CitModule"
  /api/modules:
    get:
      tags:
      - module-controller
      operationId: getAllModules
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CitModule"
  /api/modules/moduleId/{id}:
    get:
      tags:
      - module-controller
      operationId: getModuleByModuleId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CitModule"
  /api/modules/id/{id}:
    get:
      tags:
      - module-controller
      operationId: getModuleById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CitModule"
components:
  schemas:
    CitModule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        moduleId:
          type: string
        translations:
          type: array
          items:
            $ref: "#/components/schemas/ModuleTranslation"
        creationDate:
          type: string
          format: date-time
    ModuleTranslation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        language:
          type: string
          enum:
          - en
          - de
        title:
          type: string
        recommendedPrerequisites:
          type: string
        assessmentMethod:
          type: string
        learningOutcomes:
          type: string
        mediaUsed:
          type: string
        literature:
          type: string
