/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSchoolDTO } from '../model/models';
import { PageResponseDTOSchool } from '../model/models';
import { PageResponseDTOUserDTO } from '../model/models';
import { School } from '../model/models';
import { UpdateUserRoleDTO } from '../model/models';
import { UserDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createSchoolDTO 
     */
    createSchool(createSchoolDTO: CreateSchoolDTO, extraHttpRequestParams?: any): Observable<School>;

    /**
     * 
     * 
     * @param schoolId 
     */
    deleteSchool(schoolId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     * @param search 
     */
    getSchools(page?: number, size?: number, search?: string, extraHttpRequestParams?: any): Observable<PageResponseDTOSchool>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     * @param search 
     */
    getUsers(page?: number, size?: number, search?: string, extraHttpRequestParams?: any): Observable<PageResponseDTOUserDTO>;

    /**
     * 
     * 
     * @param userId 
     * @param updateUserRoleDTO 
     */
    updateUserRole(userId: string, updateUserRoleDTO: UpdateUserRoleDTO, extraHttpRequestParams?: any): Observable<UserDTO>;

}
