/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AiReviewGuidelineDTO } from '../model/models';
import { CreateAiReviewGuidelineDTO } from '../model/models';
import { UpdateAiReviewGuidelineDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AiReviewGuidelineControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createAiReviewGuidelineDTO 
     */
    createGuideline(createAiReviewGuidelineDTO: CreateAiReviewGuidelineDTO, extraHttpRequestParams?: any): Observable<AiReviewGuidelineDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteGuideline(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllGuidelines(extraHttpRequestParams?: any): Observable<Array<AiReviewGuidelineDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getGuideline(id: number, extraHttpRequestParams?: any): Observable<AiReviewGuidelineDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateAiReviewGuidelineDTO 
     */
    updateGuideline(id: number, updateAiReviewGuidelineDTO: UpdateAiReviewGuidelineDTO, extraHttpRequestParams?: any): Observable<AiReviewGuidelineDTO>;

}
