export * from './admin-user-controller.service';
import { AdminUserControllerService } from './admin-user-controller.service';
export * from './admin-user-controller.serviceInterface';
export * from './degree-program-specializations-controller.service';
import { DegreeProgramSpecializationsControllerService } from './degree-program-specializations-controller.service';
export * from './degree-program-specializations-controller.serviceInterface';
export * from './degree-programs-controller.service';
import { DegreeProgramsControllerService } from './degree-programs-controller.service';
export * from './degree-programs-controller.serviceInterface';
export * from './examination-board-controller.service';
import { ExaminationBoardControllerService } from './examination-board-controller.service';
export * from './examination-board-controller.serviceInterface';
export * from './feedback-controller.service';
import { FeedbackControllerService } from './feedback-controller.service';
export * from './feedback-controller.serviceInterface';
export * from './module-version-controller.service';
import { ModuleVersionControllerService } from './module-version-controller.service';
export * from './module-version-controller.serviceInterface';
export * from './proposal-controller.service';
import { ProposalControllerService } from './proposal-controller.service';
export * from './proposal-controller.serviceInterface';
export * from './reviewer-pre-submission-guideline-controller.service';
import { ReviewerPreSubmissionGuidelineControllerService } from './reviewer-pre-submission-guideline-controller.service';
export * from './reviewer-pre-submission-guideline-controller.serviceInterface';
export * from './user-controller.service';
import { UserControllerService } from './user-controller.service';
export * from './user-controller.serviceInterface';
export const APIS = [AdminUserControllerService, DegreeProgramSpecializationsControllerService, DegreeProgramsControllerService, ExaminationBoardControllerService, FeedbackControllerService, ModuleVersionControllerService, ProposalControllerService, ReviewerPreSubmissionGuidelineControllerService, UserControllerService];
