/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddSpecializationsToDegreeProgramDTO } from '../model/models';
import { CreateDegreeProgramDTO } from '../model/models';
import { DegreeProgramDTO } from '../model/models';
import { UpdateDegreeProgramDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DegreeProgramsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param degreeProgramId 
     * @param addSpecializationsToDegreeProgramDTO 
     */
    addSpecializationsToDegreeProgram(degreeProgramId: number, addSpecializationsToDegreeProgramDTO: AddSpecializationsToDegreeProgramDTO, extraHttpRequestParams?: any): Observable<DegreeProgramDTO>;

    /**
     * 
     * 
     * @param createDegreeProgramDTO 
     */
    createDegreeProgram(createDegreeProgramDTO: CreateDegreeProgramDTO, extraHttpRequestParams?: any): Observable<DegreeProgramDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteDegreeProgram(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllDegreePrograms(extraHttpRequestParams?: any): Observable<Array<DegreeProgramDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getDegreeProgram(id: number, extraHttpRequestParams?: any): Observable<DegreeProgramDTO>;

    /**
     * 
     * 
     * @param degreeProgramId 
     * @param degreeProgramSpecializationId 
     */
    removeSpecializationFromDegreeProgram(degreeProgramId: number, degreeProgramSpecializationId: number, extraHttpRequestParams?: any): Observable<DegreeProgramDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateDegreeProgramDTO 
     */
    updateDegreeProgram(id: number, updateDegreeProgramDTO: UpdateDegreeProgramDTO, extraHttpRequestParams?: any): Observable<DegreeProgramDTO>;

}
