/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDegreeProgramSpecializationDTO } from '../model/models';
import { DegreeProgramSpecializationDTO } from '../model/models';
import { UpdateDegreeProgramSpecializationDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DegreeProgramSpecializationsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createDegreeProgramSpecializationDTO 
     */
    createDegreeProgramSpecialization(createDegreeProgramSpecializationDTO: CreateDegreeProgramSpecializationDTO, extraHttpRequestParams?: any): Observable<DegreeProgramSpecializationDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteDegreeProgramSpecialization(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllDegreeProgramSpecializations(extraHttpRequestParams?: any): Observable<Array<DegreeProgramSpecializationDTO>>;

    /**
     * 
     * 
     * @param id 
     * @param updateDegreeProgramSpecializationDTO 
     */
    updateDegreeProgramSpecialization(id: number, updateDegreeProgramSpecializationDTO: UpdateDegreeProgramSpecializationDTO, extraHttpRequestParams?: any): Observable<DegreeProgramSpecializationDTO>;

}
