/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateExaminationBoardDTO } from '../model/models';
import { ExaminationBoardDTO } from '../model/models';
import { ExaminationBoardSummaryDTO } from '../model/models';
import { UpdateExaminationBoardDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExaminationBoardControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createExaminationBoardDTO 
     */
    createExaminationBoard(createExaminationBoardDTO: CreateExaminationBoardDTO, extraHttpRequestParams?: any): Observable<ExaminationBoardDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteExaminationBoard(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllExaminationBoards(extraHttpRequestParams?: any): Observable<Array<ExaminationBoardSummaryDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getExaminationBoard(id: number, extraHttpRequestParams?: any): Observable<ExaminationBoardDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateExaminationBoardDTO 
     */
    updateExaminationBoard(id: number, updateExaminationBoardDTO: UpdateExaminationBoardDTO, extraHttpRequestParams?: any): Observable<ExaminationBoardDTO>;

}
