/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Feedback } from '../model/models';
import { FeedbackDTO } from '../model/models';
import { FeedbackListItemDto } from '../model/models';
import { GiveFeedbackDTO } from '../model/models';
import { ModuleVersionUpdateRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FeedbackControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param feedbackId 
     */
    approveFeedback(feedbackId: number, extraHttpRequestParams?: any): Observable<Feedback>;

    /**
     * 
     * 
     */
    getFeedbacksForAuthenticatedUser(extraHttpRequestParams?: any): Observable<Array<FeedbackListItemDto>>;

    /**
     * 
     * 
     * @param feedbackId 
     */
    getModuleVersionOfFeedback(feedbackId: number, extraHttpRequestParams?: any): Observable<ModuleVersionUpdateRequestDTO>;

    /**
     * 
     * 
     * @param feedbackId 
     * @param feedbackDTO 
     */
    giveFeedback(feedbackId: number, feedbackDTO: FeedbackDTO, extraHttpRequestParams?: any): Observable<Feedback>;

    /**
     * 
     * 
     * @param feedbackId 
     * @param giveFeedbackDTO 
     */
    rejectFeedback(feedbackId: number, giveFeedbackDTO: GiveFeedbackDTO, extraHttpRequestParams?: any): Observable<Feedback>;

}
