/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProposalRequestDTO } from '../model/models';
import { ProposalViewDTO } from '../model/models';
import { ProposalsCompactDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProposalControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param proposalRequestDTO 
     */
    createProposal(proposalRequestDTO: ProposalRequestDTO, extraHttpRequestParams?: any): Observable<ProposalViewDTO>;

    /**
     * 
     * 
     * @param proposalId 
     */
    deleteProposal(proposalId: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    getCompactProposalsFromUser(extraHttpRequestParams?: any): Observable<Array<ProposalsCompactDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getProposalView(id: number, extraHttpRequestParams?: any): Observable<ProposalViewDTO>;

    /**
     * 
     * 
     * @param proposalId 
     */
    requestCoordinatorsFeedback(proposalId: number, extraHttpRequestParams?: any): Observable<ProposalViewDTO>;

    /**
     * 
     * 
     * @param proposalId 
     */
    requestExaminationBoardFeedback(proposalId: number, extraHttpRequestParams?: any): Observable<ProposalViewDTO>;

}
