/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ReviewerPreSubmissionGuidelineDto } from '../model/models';
import { ReviewerPreSubmissionGuidelineWriteDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReviewerPreSubmissionGuidelineControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param guidelineId 
     */
    _delete(guidelineId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param reviewerPreSubmissionGuidelineWriteDto 
     */
    create(reviewerPreSubmissionGuidelineWriteDto: ReviewerPreSubmissionGuidelineWriteDto, extraHttpRequestParams?: any): Observable<ReviewerPreSubmissionGuidelineDto>;

    /**
     * 
     * 
     */
    list(extraHttpRequestParams?: any): Observable<Array<ReviewerPreSubmissionGuidelineDto>>;

    /**
     * 
     * 
     * @param guidelineId 
     * @param reviewerPreSubmissionGuidelineWriteDto 
     */
    update(guidelineId: number, reviewerPreSubmissionGuidelineWriteDto: ReviewerPreSubmissionGuidelineWriteDto, extraHttpRequestParams?: any): Observable<ReviewerPreSubmissionGuidelineDto>;

}
