spring:
  application:
    name: ModuleManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/ModuleManagement
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/module-management/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/realms/module-management

  ai:
    openai:
      api-key: nss

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: compose.yaml


module-management:
  keycloak:
    client-id: module-management-client

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json