package modulemanagement.ls1.dtos;

import lombok.Data;

@Data
public class FeedbackDTO {
    private String titleFeedback;
    private boolean titleAccepted;
    private String titleDeFeedback;
    private boolean titleDeAccepted;
    private String bulletPointsFeedback;
    private boolean bulletPointsAccepted;
    private String levelFeedback;
    private boolean levelAccepted;
    private String languageFeedback;
    private boolean languageAccepted;
    private String frequencyFeedback;
    private boolean frequencyAccepted;
    private String creditsFeedback;
    private boolean creditsAccepted;
    private String durationFeedback;
    private boolean durationAccepted;
    private String hoursTotalFeedback;
    private boolean hoursTotalAccepted;
    private String hoursSelfStudyFeedback;
    private boolean hoursSelfStudyAccepted;
    private String hoursPresenceFeedback;
    private boolean hoursPresenceAccepted;
    private String hoursLectureFeedback;
    private boolean hoursLectureAccepted;
    private String hoursExerciseFeedback;
    private boolean hoursExerciseAccepted;
    private String hoursPracticalFeedback;
    private boolean hoursPracticalAccepted;
    private String hoursSeminarFeedback;
    private boolean hoursSeminarAccepted;
    private String firstSemesterAvailableFeedback;
    private boolean firstSemesterAvailableAccepted;
    private String successorModuleNameFeedback;
    private boolean successorModuleNameAccepted;
    private String examinationAchievementsFeedback;
    private boolean examinationAchievementsAccepted;
    private String examinationAchievementsPromptFeedback;
    private boolean examinationAchievementsPromptAccepted;
    private String repetitionFeedback;
    private boolean repetitionAccepted;
    private String recommendedPrerequisitesFeedback;
    private boolean recommendedPrerequisitesAccepted;
    private String contentFeedback;
    private boolean contentAccepted;
    private String contentPromptFeedback;
    private boolean contentPromptAccepted;
    private String learningOutcomesFeedback;
    private boolean learningOutcomesAccepted;
    private String learningOutcomesPromptFeedback;
    private boolean learningOutcomesPromptAccepted;
    private String teachingMethodsFeedback;
    private boolean teachingMethodsAccepted;
    private String teachingMethodsPromptFeedback;
    private boolean teachingMethodsPromptAccepted;
    private String mediaFeedback;
    private boolean mediaAccepted;
    private String literatureFeedback;
    private boolean literatureAccepted;
    private String responsiblesFeedback;
    private boolean responsiblesAccepted;
    private String lvSwsLecturerFeedback;
    private boolean lvSwsLecturerAccepted;
}
